### ISSUE TITLE
Does not work on Windows 10

### ISSUE THREAD

**Issue by evilguest** [cloudblue/connect-cli#56]
Did everything as described in the documentation:
1. Python 3.6.9 installed
2. MSYS2 installed
3. GTK3+ installed
3. Path to Mingw added to PATH (btw, documentation does have it wrong - the correct path is C:\msys64\mingw64\bin, not C:\msys2\mingw64\bin
4. Downloaded and unpacked binary file ccli.exe (btw, the link "releases" in the documentation is broken - the correct one is https://github.com/cloudblue/connect-cli/releases)
5. Note: the PIP install didn't work - I don't have this "$" prompt mentioned in the doc. Tried 'pip install' in cmd.exe - command not found. Tried in MSYS2 prompt - command not found. 
6. Edited the PATH var
Now, running ccli.exe, I get the following:
```
C:\Windows\system32>ccli


Traceback (most recent call last):
  File "cli\ccli.py", line 31, in <module>
  File "cli\ccli.py", line 15, in main
  File "cli\core\plugins.py", line 14, in load_plugins
  File "pkg_resources\__init__.py", line 2450, in load
  File "pkg_resources\__init__.py", line 2456, in resolve
ModuleNotFoundError: No module named 'connect.cli.plugins.play'
[33500] Failed to execute script ccli
```

**Comment by marcserrat** [comment]
Hi @evilguest,

can you expose please what version of the CLI tool you have? Can you check if you are running latest version 23.0?

thanks

**Comment by evilguest** [comment]
The most recent one - downloaded 20 minutes ago. 
P.S. I've found the way to run ```pip install connect-cli``` - there is a step "add pip path to the PATH var" missing in instructions.
However, this didn't change a thing - ccli.exe still outputs the same. Maybe, few more folders should be added to my PATH

**Comment by marcserrat** [comment]
hi Anton,

using pip is not for windows......just for *ix systems and seems to me that can be root cause of the issue.

please do following:

a) uninstall using pip: pip uninstall connect-cli
b) Download the single executable for windows: https://github.com/cloudblue/connect-cli/releases/download/23.0/connect-cli_23.0_windows_amd64.zip
c) Unpack the .zip and run it

please let me know about results
