### ISSUE TITLE
Exception is thrown if report format is unavailable

### ISSUE THREAD

**Issue by gab832** [cloudblue/connect-cli#83]
If I create a report specifying with the option -f for an output format that does not exist it raises an exception instead of notifying the user with an error message.

Example:

ccli report execute my_awesome_report_pdf -d my_awesome_project -f pdf

Traceback (most recent call last):
  File "/Users/galonso00/.env/cli/bin/ccli", line 8, in <module>
    sys.exit(main())
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/connect/cli/ccli.py", line 16, in main
    cli(prog_name='ccli', standalone_mode=False)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/connect/cli/core/base.py", line 14, in invoke
    return super().invoke(ctx)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/connect/cli/plugins/report/commands.py", line 58, in cmd_execute_report
    execute_report(config, reports_dir, report_id, output_file, output_format)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/connect/cli/plugins/report/helpers.py", line 118, in execute_report
    inputs = get_report_inputs(config, client, report, output_format)
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/connect/cli/plugins/report/wizard.py", line 271, in get_report_inputs
    intro=generate_intro(config, report, output_format),
  File "/Users/galonso00/.env/cli/lib/python3.9/site-packages/connect/cli/plugins/report/wizard.py", line 238, in generate_intro
    output_format=output_formats[output_format],
KeyError: 'pdf'

**Comment by ffaraoneim** [comment]
Fixed
